/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import model.Cliente;
import model.Habitacion;
import model.HotelJWMarriottQuito;
import model.Reserva;
import model.Factura;

import exception.HabitacionNoDisponibleException;
import exception.ReservaInvalidaException;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JOptionPane;


/**
 *
 * @author USER-PC
 */
public class VentanaReserva extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaReserva.class.getName());
    private HotelJWMarriottQuito hotel;
    /**
     * Creates new form VentanaReserva
     */
    public VentanaReserva() { this(model.DataStore.cargar()); }

    public VentanaReserva(HotelJWMarriottQuito hotel) {
        initComponents();
        
        this.hotel = hotel;
        
        setTitle("Realizar reserva");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cargarClientes();
        cargarHabitaciones();
        
    }
    private void cargarClientes(){
        cmbClientes.removeAllItems();
        for (Cliente cliente : hotel.getClientes()){
            cmbClientes.addItem(cliente.getNombre() + " " + cliente.getApellido() + " - " + cliente.getCedula());
        }
    }
    
    private void cargarHabitaciones() {
    cmbHabitaciones.removeAllItems();

    for (Habitacion habitacion
            : hotel.buscarHabitacionesDisponibles()) {

        cmbHabitaciones.addItem(
                habitacion.getNumero()
                + " - "
                + habitacion.getClass().getSimpleName()
                + " - $"
                + String.format("%.2f", habitacion.calcularPrecio())
        );
    }
}
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCliente = new javax.swing.JLabel();
        lblHabitacion = new javax.swing.JLabel();
        lblFechaEntrada = new javax.swing.JLabel();
        lblFechaSalida = new javax.swing.JLabel();
        cmbClientes = new javax.swing.JComboBox<>();
        cmbHabitaciones = new javax.swing.JComboBox<>();
        btnReservar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtFechaEntrada = new javax.swing.JTextField();
        txtFechaSalida = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCliente.setText("Cliente");

        lblHabitacion.setText("Habitacion");

        lblFechaEntrada.setText("Fecha de entrada");

        lblFechaSalida.setText("Fecha de salida");

        cmbClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbHabitaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnReservar.setText("Reservar");
        btnReservar.addActionListener(this::btnReservarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblHabitacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbClientes, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblFechaSalida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFechaEntrada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFechaEntrada, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(btnReservar))
                            .addComponent(txtFechaSalida))
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblCliente)
                .addGap(1, 1, 1)
                .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHabitacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFechaEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFechaSalida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservar)
                    .addComponent(btnCancelar))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        // TODO add your handling code here:
        
        if (cmbClientes.getSelectedIndex() == -1) {
        JOptionPane.showMessageDialog(
                this,
                "No hay clientes disponibles. Registre un cliente primero.",
                "Sin clientes",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }
        
        if (cmbHabitaciones.getSelectedIndex() == -1) {
        JOptionPane.showMessageDialog(
                this,
                "No hay habitaciones disponibles.",
                "Sin habitaciones",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }
        
        
        String textoEntrada = txtFechaEntrada.getText().trim();
        String textoSalida = txtFechaSalida.getText().trim();
         if (textoEntrada.isEmpty() || textoSalida.isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Debe ingresar la fecha de entrada y la fecha de salida.",
                "Fechas incompletas",
                JOptionPane.ERROR_MESSAGE
        );
        return;
    }
         
         SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            formato.setLenient(false);
         
          try {
        Date fechaEntrada = formato.parse(textoEntrada);
        Date fechaSalida = formato.parse(textoSalida);

        int indiceCliente = cmbClientes.getSelectedIndex();
        int indiceHabitacion = cmbHabitaciones.getSelectedIndex();

        Cliente clienteSeleccionado =
                hotel.getClientes().get(indiceCliente);

        Habitacion habitacionSeleccionada =
                hotel.buscarHabitacionesDisponibles().get(indiceHabitacion);

        String idReserva = "RES-" + (hotel.getReservas().size() + 1);

        Reserva nuevaReserva = new Reserva(
                idReserva,
                clienteSeleccionado,
                habitacionSeleccionada,
                fechaEntrada,
                fechaSalida
        );

        hotel.registrarReserva(nuevaReserva);

        Factura factura = new Factura(
                "FAC-" + String.format("%03d", hotel.getReservas().size()),
                nuevaReserva
        );

        JOptionPane.showMessageDialog(
                this,
                "Reserva registrada correctamente.\n\n"
                + "ID de reserva: " + idReserva + "\n"
                + "Cliente: " + clienteSeleccionado.getNombre()
                + " " + clienteSeleccionado.getApellido() + "\n"
                + "Habitación: " + habitacionSeleccionada.getNumero() + "\n"
                + "Total: $" + String.format("%.2f", nuevaReserva.calcularTotal()),
                "Reserva exitosa",
                JOptionPane.INFORMATION_MESSAGE
        );

        txtFechaEntrada.setText("");
        txtFechaSalida.setText("");

        cargarHabitaciones();

    } catch (ParseException e) {
        JOptionPane.showMessageDialog(
                this,
                "Las fechas deben tener el formato AAAA-MM-DD.\n"
                + "Ejemplo: 2026-07-20",
                "Formato de fecha incorrecto",
                JOptionPane.ERROR_MESSAGE
        );

    } catch (Exception e) {
        JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "No se pudo registrar la reserva",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnReservarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaReserva().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnReservar;
    private javax.swing.JComboBox<String> cmbClientes;
    private javax.swing.JComboBox<String> cmbHabitaciones;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblFechaEntrada;
    private javax.swing.JLabel lblFechaSalida;
    private javax.swing.JLabel lblHabitacion;
    private javax.swing.JTextField txtFechaEntrada;
    private javax.swing.JTextField txtFechaSalida;
    // End of variables declaration//GEN-END:variables
}
